import { NextRequest, NextResponse } from 'next/server';
import { parse } from 'node-html-parser';

export const maxDuration = 30;

// ── LaTeX helpers ─────────────────────────────────────────────────────────────

/** Escape all LaTeX special characters in a plain-text string. */
function esc(s: string): string {
  return s
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g,  '\\&')
    .replace(/%/g,  '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g,  '\\#')
    .replace(/_/g,  '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g,  '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/</g,  '\\textless{}')
    .replace(/>/g,  '\\textgreater{}')
    .replace(/–/g,  '--')
    .replace(/—/g,  '---')
    .replace(/'/g,  "'")
    .replace(/'/g,  "'")
    .replace(/"/g,  "''")
    .replace(/"/g,  "``")
    .replace(/…/g,  '\\ldots{}')
    .replace(/₹/g,  '\\rupee{}')
    .replace(/•/g,  '\\textbullet{}');
}

function txt(el: any): string {
  return el?.text?.trim() ?? '';
}

// ── Document builder ──────────────────────────────────────────────────────────

function buildLatex(html: string): string {
  const root = parse(html);
  const lines: string[] = [];

  // ── Preamble ────────────────────────────────────────────────────────────────
  lines.push(String.raw`% ── Generated by Job Tailor · jobtailor.in ────────────────────────────────
% Upload this file to https://overleaf.com → New Project → Upload → Recompile
% ─────────────────────────────────────────────────────────────────────────────
\documentclass[10pt,letterpaper]{article}

\usepackage[top=0.5in,bottom=0.5in,left=0.65in,right=0.65in]{geometry}
\usepackage[hidelinks]{hyperref}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{microtype}
\usepackage{xcolor}

% ── Typography ────────────────────────────────────────────────────────────────
\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}
\hypersetup{colorlinks=true,urlcolor=black,linkcolor=black}

% ── Section title ─────────────────────────────────────────────────────────────
\titleformat{\section}
  {\vspace{2pt}\scshape\raggedright\large\bfseries}
  {}{0em}{}[\color{black}\titlerule\vspace{2pt}]
\titlespacing*{\section}{0pt}{5pt}{3pt}

% ── Bullet list ───────────────────────────────────────────────────────────────
\setlist[itemize]{leftmargin=0.18in,label=\textbullet,itemsep=1pt,parsep=0pt,topsep=2pt}

% ── Custom commands ───────────────────────────────────────────────────────────
\newcommand{\entry}[3]{%
  \vspace{3pt}\textbf{#1} \hfill #3 \\
  \textit{\small #2}\vspace{1pt}}
\newcommand{\skillrow}[2]{\textbf{#1:} #2 \\[1pt]}

\begin{document}
`);

  // ── Header ──────────────────────────────────────────────────────────────────
  const name = txt(root.querySelector('h1'));
  const targetRole = txt(root.querySelector('.target-role'));
  lines.push(`% ── HEADER ──────────────────────────────────────────────────────────────────`);
  lines.push(`\\begin{center}`);
  lines.push(`  {\\Huge\\bfseries ${esc(name)}}\\\\[3pt]`);
  if (targetRole) {
    lines.push(`  {\\large\\textit{${esc(targetRole)}}}\\\\[3pt]`);
  }

  const contactParts: string[] = [];
  (root.querySelectorAll('.contact-item') as any[]).forEach((item: any) => {
    const link = item.querySelector('a');
    const span = item.querySelector('span');
    if (link) {
      const href = link.getAttribute('href') ?? '';
      const label = txt(link);
      if (href.startsWith('mailto:')) {
        contactParts.push(`\\href{${href}}{${esc(label)}}`);
      } else if (href.startsWith('http')) {
        contactParts.push(`\\href{${href}}{${esc(label)}}`);
      } else {
        contactParts.push(esc(label));
      }
    } else if (span) {
      contactParts.push(esc(txt(span)));
    }
  });

  if (contactParts.length) {
    lines.push(`  \\small ${contactParts.join(' $\\vert$\\; ')}`);
  }
  lines.push(`\\end{center}\n`);

  // ── Sections ────────────────────────────────────────────────────────────────
  const sections = root.querySelectorAll('.section') as any[];

  for (const sec of sections) {
    const secTitle: string = sec.querySelector('.section-title')?.text?.trim() ?? '';
    if (!secTitle) continue;
    const lower = secTitle.toLowerCase();

    lines.push(`% ── ${secTitle.toUpperCase()} ${'─'.repeat(Math.max(0, 72 - secTitle.length))}`);
    lines.push(`\\section{${esc(secTitle)}}\n`);

    // ── Summary ───────────────────────────────────────────────────────────────
    if (lower === 'summary') {
      const p = sec.querySelector('p');
      const summaryText = txt(p);
      if (summaryText) lines.push(esc(summaryText) + '\n');

    // ── Skills ────────────────────────────────────────────────────────────────
    } else if (lower === 'skills') {
      (sec.querySelectorAll('.skill-row') as any[]).forEach((row: any) => {
        const cat = row.querySelector('.skill-cat')?.text?.trim() ?? '';
        const val = row.querySelector('.skill-val')?.text?.trim() ?? '';
        lines.push(`\\skillrow{${esc(cat)}}{${esc(val)}}`);
      });
      lines.push('');

    // ── Experience ────────────────────────────────────────────────────────────
    } else if (lower === 'experience') {
      (sec.querySelectorAll('.job') as any[]).forEach((job: any) => {
        const title   = job.querySelector('.job-title')?.text?.trim()   ?? '';
        const date    = job.querySelector('.job-date')?.text?.trim()    ?? '';
        const company = job.querySelector('.job-company')?.text?.trim() ?? '';
        lines.push(`\\entry{${esc(title)}}{${esc(company)}}{${esc(date)}}`);
        lines.push(`\\begin{itemize}`);
        (job.querySelectorAll('li') as any[]).forEach((li: any) => {
          lines.push(`  \\item ${esc(li.text.trim())}`);
        });
        lines.push(`\\end{itemize}\n`);
      });

    // ── Projects ──────────────────────────────────────────────────────────────
    } else if (lower === 'projects') {
      (sec.querySelectorAll('.project-block') as any[]).forEach((proj: any) => {
        const projName = proj.querySelector('.project-name')?.text?.trim() ?? '';
        const projDate = proj.querySelector('.job-date')?.text?.trim()    ?? '';
        // Build links string for the second arg of \entry
        const linkEls  = (proj.querySelectorAll('.project-links a') as any[]);
        const linkParts = linkEls.map((a: any) => {
          const href  = a.getAttribute('href') ?? '';
          const label = a.text.trim();
          return href ? `\\href{${esc(href)}}{${esc(label)}}` : esc(label);
        });
        const linksStr = linkParts.join(' \\quad\\textbullet\\quad ');
        lines.push(`\\entry{${esc(projName)}}{${linksStr || ''}}{${esc(projDate)}}`);
        lines.push(`\\begin{itemize}`);
        (proj.querySelectorAll('li') as any[]).forEach((li: any) => {
          lines.push(`  \\item ${esc(li.text.trim())}`);
        });
        lines.push(`\\end{itemize}\n`);
      });

    // ── Education ─────────────────────────────────────────────────────────────
    } else if (lower === 'education') {
      const degree = sec.querySelector('.edu-degree')?.text?.trim() ?? '';
      const year   = sec.querySelector('.edu-year')?.text?.trim()   ?? '';
      const school = sec.querySelector('.edu-school')?.text?.trim() ?? '';
      lines.push(`\\entry{${esc(degree)}}{${esc(school)}}{${esc(year)}}`);
      const lis = sec.querySelectorAll('li') as any[];
      if (lis.length) {
        lines.push(`\\begin{itemize}`);
        lis.forEach((li: any) => lines.push(`  \\item ${esc(li.text.trim())}`));
        lines.push(`\\end{itemize}`);
      }
      lines.push('');

    // ── Awards / Certifications (award-header pattern) ────────────────────────
    } else {
      (sec.querySelectorAll('.award-header') as any[]).forEach((hdr: any, i: number) => {
        const aTitle = hdr.querySelector('.award-title')?.text?.trim() ?? '';
        const aYear  = hdr.querySelector('.award-year')?.text?.trim()  ?? '';
        const nextEl = hdr.nextElementSibling as any;
        const org    = nextEl?.classList?.contains('award-org') ? nextEl.text.trim() : '';

        if (i > 0) lines.push('');
        lines.push(`\\textbf{${esc(aTitle)}} \\hfill ${esc(aYear)} \\\\`);
        if (org) lines.push(`\\textit{${esc(org)}}`);

        const afterOrg = org ? nextEl?.nextElementSibling : nextEl;
        if (afterOrg?.tagName === 'UL') {
          lines.push(`\\begin{itemize}`);
          (afterOrg.querySelectorAll('li') as any[]).forEach((li: any) => {
            lines.push(`  \\item ${esc(li.text.trim())}`);
          });
          lines.push(`\\end{itemize}`);
        }
      });
      lines.push('');
    }
  }

  lines.push(`\\end{document}`);
  return lines.join('\n');
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null);
  if (!body?.html) {
    return NextResponse.json({ error: 'html is required' }, { status: 400 });
  }

  const latex = buildLatex(body.html as string);
  const name  = (parse(body.html as string).querySelector('h1')?.text?.trim() ?? 'Resume')
    .replace(/\s+/g, '_');

  return new NextResponse(latex, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="${name}_Resume.tex"`,
      'Cache-Control': 'no-store',
    },
  });
}
